db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/gym_db
  username: gymuser
  password: gympass

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl:
    auto: validate

liquibase:
  changelog:
    master: classpath:db/migration/master.xml

storage:
  data:
    trainee: src/main/resources/data/trainees.csv
    trainer: src/main/resources/data/trainers.csv
    training: src/main/resources/data/trainings.csv

app:
  api:
    base-path: /api/v1