spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    changelog: classpath:db/migration/master.xml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  api:
    base-path: /api/v1